### ISSUE TITLE
Issue with import

### ISSUE THREAD

**Issue by daRasmussen** [Esri/share-widget#12]
Hello/ 

I have a hard time to import this widget into my project. I errors on the following lines in 

`ShareWidget.tsx`

`import i18n = require("dojo/i18n!./Share/nls/resources");`

`import { substitute } from "esri/core/lang";`

Not sure how to resolve these issues.

**Comment by rslibed** [comment]
For `import i18n = require("dojo/i18n!./Share/nls/resources");` dojo/i18n is used to load in the strings. The reason for this is to pull in the translated strings from the file of the corresponding locale. 

The error for `import { substitute } from "esri/core/lang";` are due to the typings not being available. I suggest creating an `updates.d.ts` file and creating custom typings to clear the errors in the console.

**Comment by Schnoerkel** [comment]
If you are using 4.12 or later use `import { substitute } from "esri/intl";` also argument order changed from `substitute(data,"template") to substitute("template",data)` see [https://developers.arcgis.com/javascript/latest/api-reference/esri-intl.html#substitute](https://developers.arcgis.com/javascript/latest/api-reference/esri-intl.html#substitute)

**Comment by rslibed** [comment]
Updated source to use `esri/intl.substitute`. Issues should now be resolved. Closing issue. Feel free to reopen if needed.
